FROM centos:latest
MAINTAINER CVUSK

ENV container docker
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;
VOLUME [ "/sys/fs/cgroup" ]

# yum install packages
WORKDIR /opt/
RUN rpm -ivh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
RUN yum -y groupinstall "Development Tools"
RUN yum -y install epel-release && \
    yum -y install zip wget bzip2 java-1.8.0-openjdk java-1.8.0-openjdk-devel tar unzip libXdmcp && \
    yum -y install vi vim sudo yum-utils policycoreutils selinux-policy-targeted openssh postgresql-devel && \
    yum -y install libXdmcp libcurl libcurl-devel libxml2-devel openssl-devel libjpeg-turbo-devel libpng-devel gcc
RUN wget http://mirror.centos.org/centos/7/os/x86_64/Packages/texlive-epsf-doc-svn21461.2.7.4-38.el7.noarch.rpm && \
    wget http://mirror.centos.org/centos/7/os/x86_64/Packages/texlive-epsf-svn21461.2.7.4-38.el7.noarch.rpm && \
    wget http://mirror.centos.org/centos/7/os/x86_64/Packages/texinfo-tex-5.1-4.el7.x86_64.rpm && \
    yum -y localinstall texlive-epsf-doc-svn21461.2.7.4-38.el7.noarch.rpm texlive-epsf-svn21461.2.7.4-38.el7.noarch.rpm texinfo-tex-5.1-4.el7.x86_64.rpm
RUN yum -y install R
RUN wget https://download2.rstudio.org/rstudio-server-rhel-1.0.143-x86_64.rpm && \
    yum -y install --nogpgcheck rstudio-server-rhel-1.0.143-x86_64.rpm
RUN yum -y update && \
    rm -rf /var/cache/yum/* && \
    rm -rf /opt/texlive-epsf-doc-svn21461.2.7.4-38.el7.noarch.rpm && \
    rm -rf /opt/texlive-epsf-svn21461.2.7.4-38.el7.noarch.rpm && \
    rm -rf /opt/texinfo-tex-5.1-4.el7.x86_64.rpm && \
    rm -rf /opt/rstudio-server-rhel-1.0.143-x86_64.rpm && \
    yum clean all
ENV JAVA_HOME=/usr/lib/jvm/java-1.8.0

WORKDIR /opt/
RUN echo "r <- getOption('repos'); r['CRAN'] <- 'http://cran.us.r-project.org'; options(repos = r);" > ~/.Rprofile
RUN Rscript -e "install.packages('yhatr')"
RUN Rscript -e "install.packages('ggplot2')"
RUN Rscript -e "install.packages('plyr')"
RUN Rscript -e "install.packages('reshape2')"
RUN Rscript -e "install.packages('forecast')"
RUN Rscript -e "install.packages('stringr')"
RUN Rscript -e "install.packages('lubridate')"
RUN Rscript -e "install.packages('randomForest')"
RUN Rscript -e "install.packages('rpart')"
RUN Rscript -e "install.packages('e1071')"
RUN Rscript -e "install.packages('kknn')"
RUN Rscript -e "install.packages('txtplot')"
RUN Rscript -e "install.packages('httr')"
RUN Rscript -e "install.packages('jsonlite')"
RUN Rscript -e "install.packages('dplyr')"
RUN Rscript -e "install.packages('caret')"
RUN Rscript -e "install.packages('devtools')"
RUN Rscript -e "install.packages('reshape2')"
RUN Rscript -e "install.packages('xgboost')"
RUN Rscript -e "install.packages('magrittr')"

RUN sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config

RUN export PATH=/usr/lib/rstudio-server/bin/:$PATH
RUN useradd ruser
RUN echo "ruser:ruser" | chpasswd

RUN yum -y install initscripts

WORKDIR /opt/
EXPOSE 8787
